"""empty message

Revision ID: 8fc887725d8a
Revises: 4799cf60a304
Create Date: 2022-12-02 01:59:42.016942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc887725d8a'
down_revision = '4799cf60a304'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
