"""empty message

Revision ID: fa7f7d4e4513
Revises: 
Create Date: 2022-11-27 23:55:02.128760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7f7d4e4513'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Administrator',
    sa.Column('idAdministrator', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=25), nullable=False),
    sa.Column('LastName', sa.String(length=225), nullable=False),
    sa.Column('phone', sa.String(length=225), nullable=False),
    sa.PrimaryKeyConstraint('idAdministrator')
    )
    op.create_table('Car',
    sa.Column('idCar', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=225), nullable=True),
    sa.Column('model', sa.String(length=225), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('seatsNum', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('idCar')
    )
    op.create_table('Passenger',
    sa.Column('idPassenger', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=225), nullable=True),
    sa.Column('LastName', sa.String(length=225), nullable=True),
    sa.Column('phone', sa.String(length=225), nullable=True),
    sa.Column('documentNum', sa.String(length=225), nullable=True),
    sa.Column('address', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('idPassenger')
    )
    op.create_table('RentalService',
    sa.Column('idService', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=True),
    sa.Column('email', sa.String(length=225), nullable=True),
    sa.Column('phone', sa.String(length=225), nullable=True),
    sa.Column('website', sa.String(length=225), nullable=True),
    sa.Column('address', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('idService')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RentalService')
    op.drop_table('Passenger')
    op.drop_table('Car')
    op.drop_table('Administrator')
    # ### end Alembic commands ###
